delete product;
--alter table manufacturer add column active boolean not null;

INSERT INTO PRODUCT_TYPE VALUES(1,'Electronics');

INSERT INTO PRODUCT VALUES(1,'Product_1','PR0001','Sample Product','Unilever','',TO_DATE('25/07/2017', 'DD/MM/YYYY'),'best before 3 months','100',1);
INSERT INTO PRODUCT VALUES(2,'Product_2','PR0002','Sample Product','Unilever','',TO_DATE('25/07/2017', 'DD/MM/YYYY'),'best before 3 months','200',1);
INSERT INTO PRODUCT VALUES(3,'Product_3','PR0003','Sample Product','Unilever','',TO_DATE('25/07/2017', 'DD/MM/YYYY'),'best before 3 months','300',1);

INSERT INTO DELIVERY VALUES(1,TO_DATE('25/07/2017', 'DD/MM/YYYY'),'address1','Delivered','PickUp');

INSERT INTO CUSTOMER_ORDER VALUES(1,12345,TO_DATE('25/07/2017', 'DD/MM/YYYY'),'100','Closed','CASH','Success',1);
INSERT INTO CUSTOMER_ORDER VALUES(2,12345,TO_DATE('25/07/2017', 'DD/MM/YYYY'),'100','Closed','CASH','Success',1);
INSERT INTO CUSTOMER_ORDER VALUES(3,12345,TO_DATE('25/07/2017', 'DD/MM/YYYY'),'100','Closed','CASH','Success',1);

INSERT INTO INVENTORY VALUES(1,true,'location1');
INSERT INTO INVENTORY VALUES(2,true,'location2');

INSERT INTO INVENTORY_PRODUCT VALUES(1,1);
INSERT INTO INVENTORY_PRODUCT VALUES(1,2);
INSERT INTO INVENTORY_PRODUCT VALUES(2,3);

INSERT INTO PRODUCT_INVENTORY VALUES(1,1);
INSERT INTO PRODUCT_INVENTORY VALUES(2,1);
INSERT INTO PRODUCT_INVENTORY VALUES(3,2);

INSERT INTO PRODUCT_ORDER VALUES(1,1);
INSERT INTO PRODUCT_ORDER VALUES(2,2);
INSERT INTO PRODUCT_ORDER VALUES(3,3);

INSERT INTO ORDER_PRODUCT VALUES(1,1);
INSERT INTO ORDER_PRODUCT VALUES(2,2);
INSERT INTO ORDER_PRODUCT VALUES(3,3);